import js from '@eslint/js'
import * as typescriptPlugin from '@typescript-eslint/eslint-plugin'
import typescriptParser from '@typescript-eslint/parser'
import prettierConfig from 'eslint-config-prettier'
import * as importPlugin from 'eslint-plugin-import'
import * as prettierPlugin from 'eslint-plugin-prettier'
import * as simpleImportSortPlugin from 'eslint-plugin-simple-import-sort'
import * as solidPlugin from 'eslint-plugin-solid'
import * as vitestPlugin from 'eslint-plugin-vitest'
import globals from 'globals'

const config = [
  {ignores: ['src/routeTree.gen.ts']},
  // Add ESLint recommended rules as base configuration
  js.configs.recommended,
  {
    files: ['**/*.{js,mjs,cjs,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parser: typescriptParser,
      globals: {...globals.browser, ...globals.node},
      parserOptions: {ecmaFeatures: {jsx: true}, project: './tsconfig.json', tsconfigRootDir: import.meta.dirname},
    },
    settings: {
      // Configure import resolver for TypeScript with Bun
      'import/resolver': {'typescript-bun': {alwaysTryTypes: true}},
    },
    plugins: {
      import: importPlugin,
      solid: solidPlugin,
      vitest: vitestPlugin,
      '@typescript-eslint': typescriptPlugin,
      prettier: prettierPlugin,
      'simple-import-sort': simpleImportSortPlugin,
    },
    rules: {
      // eslint-plugin-solid rules with default values
      'solid/components-return-once': 'error',
      'solid/event-handlers': ['error', {ignoreCase: false, warnOnSpread: false}],
      'solid/imports': 'error',
      'solid/jsx-no-duplicate-props': 'error',
      'solid/jsx-no-script-url': 'error',
      'solid/jsx-no-undef': 'error',
      'solid/jsx-uses-vars': 'error',
      'solid/no-destructure': 'error',
      'solid/no-innerhtml': ['error', {allowStatic: true}],
      'solid/no-react-deps': 'error',
      'solid/no-react-specific-props': 'error',
      'solid/no-unknown-namespaces': 'off',
      'solid/prefer-for': 'error',
      'solid/reactivity': 'error',
      'solid/self-closing-comp': 'error',
      'solid/style-prop': ['error', {styleProps: ['style', 'css']}],
      'solid/no-array-handlers': 'off',
      'solid/prefer-classlist': 'off',
      'solid/prefer-show': 'off',
      'solid/no-proxy-apis': 'off',

      // eslint-plugin-vitest rules with default values
      'vitest/consistent-test-it': 'off',
      'vitest/expect-expect': 'error',
      'vitest/max-expects': 'off',
      'vitest/max-nested-describe': 'off',
      'vitest/no-alias-methods': 'off',
      'vitest/no-commented-out-tests': 'error',
      'vitest/no-conditional-expect': 'error',
      'vitest/no-conditional-in-test': 'error',
      'vitest/no-conditional-tests': 'error',
      'vitest/no-disabled-tests': 'error',
      'vitest/no-done-callback': 'error',
      'vitest/no-duplicate-hooks': 'error',
      'vitest/no-focused-tests': 'error',
      'vitest/no-hooks': 'off',
      'vitest/no-identical-title': 'error',
      'vitest/no-interpolation-in-snapshots': 'error',
      'vitest/no-large-snapshots': 'off',
      'vitest/no-mocks-import': 'error',
      'vitest/no-restricted-matchers': 'off',
      'vitest/no-restricted-vi-methods': 'off',
      'vitest/no-standalone-expect': 'error',
      'vitest/no-test-prefixes': 'error',
      'vitest/no-test-return-statement': 'error',
      'vitest/prefer-called-with': 'off',
      'vitest/prefer-comparison-matcher': 'off',
      'vitest/prefer-each': 'off',
      'vitest/prefer-equality-matcher': 'off',
      'vitest/prefer-expect-resolves': 'off',
      'vitest/prefer-hooks-in-order': 'error',
      'vitest/prefer-hooks-on-top': 'error',
      'vitest/prefer-lowercase-title': 'off',
      'vitest/prefer-mock-promise-shorthand': 'off',
      'vitest/prefer-snapshot-hint': 'off',
      'vitest/prefer-spy-on': 'off',
      'vitest/prefer-strict-equal': 'off',
      'vitest/prefer-to-be': 'off',
      'vitest/prefer-to-be-falsy': 'off',
      'vitest/prefer-to-be-object': 'off',
      'vitest/prefer-to-be-truthy': 'off',
      'vitest/prefer-to-contain': 'off',
      'vitest/prefer-to-have-length': 'off',
      'vitest/prefer-todo': 'error',
      'vitest/require-hook': 'off',
      'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
      'vitest/require-to-throw-message': 'off',
      'vitest/require-top-level-describe': 'off',
      'vitest/valid-describe-callback': 'error',
      'vitest/valid-expect': 'error',
      'vitest/valid-title': 'error',

      // @typescript-eslint rules with default values
      '@typescript-eslint/adjacent-overload-signatures': 'error',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/ban-ts-comment': 'error',
      '@typescript-eslint/ban-tslint-comment': 'error',
      '@typescript-eslint/class-literal-property-style': 'off',
      '@typescript-eslint/class-methods-use-this': 'off',
      '@typescript-eslint/consistent-generic-constructors': 'off',
      '@typescript-eslint/consistent-indexed-object-style': 'off',
      '@typescript-eslint/consistent-return': 'off',
      '@typescript-eslint/consistent-type-assertions': 'off',
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/consistent-type-exports': 'error',
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/default-param-last': 'off',
      '@typescript-eslint/dot-notation': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-member-accessibility': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/init-declarations': 'off',
      '@typescript-eslint/max-params': 'off',
      '@typescript-eslint/member-ordering': 'off',
      '@typescript-eslint/method-signature-style': 'off',
      '@typescript-eslint/naming-convention': 'off',
      '@typescript-eslint/no-array-constructor': 'error',
      '@typescript-eslint/no-array-delete': 'error',
      '@typescript-eslint/no-base-to-string': 'error',
      '@typescript-eslint/no-confusing-non-null-assertion': 'error',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/no-duplicate-enum-values': 'error',
      '@typescript-eslint/no-duplicate-type-constituents': 'error',
      '@typescript-eslint/no-dynamic-delete': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-empty-interface': 'error',
      '@typescript-eslint/no-empty-object-type': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-extra-non-null-assertion': 'error',
      '@typescript-eslint/no-extraneous-class': 'off',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-for-in-array': 'error',
      '@typescript-eslint/no-implied-eval': 'error',
      '@typescript-eslint/no-import-type-side-effects': 'off',
      '@typescript-eslint/no-inferrable-types': 'error',
      '@typescript-eslint/no-invalid-this': 'off',
      '@typescript-eslint/no-invalid-void-type': 'error',
      '@typescript-eslint/no-loop-func': 'off',
      '@typescript-eslint/no-loss-of-precision': 'error',
      '@typescript-eslint/no-magic-numbers': 'off',
      '@typescript-eslint/no-meaningless-void-operator': 'error',
      '@typescript-eslint/no-misused-new': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/no-mixed-enums': 'error',
      '@typescript-eslint/no-namespace': 'error',
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-redeclare': 'error',
      '@typescript-eslint/no-redundant-type-constituents': 'error',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-restricted-imports': 'off',
      '@typescript-eslint/no-shadow': 'off',
      '@typescript-eslint/no-this-alias': 'error',
      '@typescript-eslint/no-throw-literal': 'off',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'off',
      '@typescript-eslint/no-unnecessary-qualifier': 'off',
      '@typescript-eslint/no-unnecessary-template-expression': 'off',
      '@typescript-eslint/no-unnecessary-type-arguments': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',
      '@typescript-eslint/no-unnecessary-type-constraint': 'error',
      '@typescript-eslint/no-unnecessary-type-parameters': 'off',
      '@typescript-eslint/no-unsafe-argument': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-declaration-merging': 'error',
      '@typescript-eslint/no-unsafe-enum-comparison': 'error',
      '@typescript-eslint/no-unsafe-function-type': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-unary-minus': 'error',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/no-useless-constructor': 'off',
      '@typescript-eslint/no-useless-empty-export': 'off',
      '@typescript-eslint/no-wrapper-object-types': 'error',
      '@typescript-eslint/non-nullable-type-assertion-style': 'off',
      '@typescript-eslint/only-throw-error': 'off',
      '@typescript-eslint/parameter-properties': 'off',
      '@typescript-eslint/prefer-as-const': 'error',
      '@typescript-eslint/prefer-destructuring': 'off',
      '@typescript-eslint/prefer-enum-initializers': 'off',
      '@typescript-eslint/prefer-find': 'off',
      '@typescript-eslint/prefer-for-of': 'off',
      '@typescript-eslint/prefer-function-type': 'off',
      '@typescript-eslint/prefer-includes': 'off',
      '@typescript-eslint/prefer-literal-enum-member': 'error',
      '@typescript-eslint/prefer-namespace-keyword': 'error',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/prefer-promise-reject-errors': 'off',
      '@typescript-eslint/prefer-readonly': 'off',
      '@typescript-eslint/prefer-readonly-parameter-types': 'off',
      '@typescript-eslint/prefer-reduce-type-parameter': 'off',
      '@typescript-eslint/prefer-regexp-exec': 'off',
      '@typescript-eslint/prefer-return-this-type': 'off',
      '@typescript-eslint/prefer-string-starts-ends-with': 'off',
      '@typescript-eslint/prefer-ts-expect-error': 'error',
      '@typescript-eslint/promise-function-async': 'off',
      '@typescript-eslint/require-array-sort-compare': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/restrict-plus-operands': 'error',
      '@typescript-eslint/restrict-template-expressions': 'error',
      '@typescript-eslint/return-await': 'off',
      '@typescript-eslint/strict-boolean-expressions': 'off',
      '@typescript-eslint/switch-exhaustiveness-check': 'off',
      '@typescript-eslint/triple-slash-reference': 'error',
      '@typescript-eslint/typedef': 'off',
      '@typescript-eslint/unbound-method': 'error',
      '@typescript-eslint/unified-signatures': 'off',
      '@typescript-eslint/use-unknown-in-catch-clause-variable': 'off',

      // eslint-plugin-prettier rules with default values
      'prettier/prettier': 'error',

      // eslint-plugin-simple-import-sort rules with default values
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',

      // eslint-plugin-import rules to enforce named exports
      'import/no-default-export': 'error',
      'import/prefer-default-export': 'off',
      'import/group-exports': 'off',

      // Core ESLint rules with defaults, except where they conflict with Prettier
      // Core ESLint rules with defaults, except where they conflict with Prettier
      'accessor-pairs': 'off',
      'array-callback-return': 'off',
      'arrow-body-style': ['error', 'always'],
      'arrow-parens': ['error', 'always'],
      'block-scoped-var': 'off',
      camelcase: 'off',
      'capitalized-comments': 'off',
      'class-methods-use-this': 'off',
      complexity: 'off',
      'consistent-return': 'off',
      'consistent-this': 'off',
      curly: ['error', 'all'],
      'default-case': 'off',
      'default-case-last': 'off',
      'default-param-last': 'off',
      'dot-notation': 'off',
      eqeqeq: 'off',
      'for-direction': 'error',
      'func-name-matching': 'off',
      'func-names': 'off',
      'func-style': ['error', 'expression', {allowArrowFunctions: true}],
      'grouped-accessor-pairs': 'off',
      'guard-for-in': 'off',
      'id-denylist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'init-declarations': 'off',
      'logical-assignment-operators': 'off',
      'max-classes-per-file': 'off',
      'max-depth': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'multiline-comment-style': 'off',
      'new-cap': 'off',
      'no-alert': 'off',
      'no-array-constructor': 'off',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'off',
      'no-bitwise': 'off',
      'no-caller': 'off',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-console': 'off',
      'no-constant-condition': 'error',
      'no-constructor-return': 'off',
      'no-continue': 'off',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-div-regex': 'off',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'off',
      'no-else-return': 'off',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-function': 'off',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'off',
      'no-eq-null': 'off',
      'no-eval': 'off',
      'no-ex-assign': 'error',
      'no-extend-native': 'off',
      'no-extra-bind': 'off',
      'no-extra-boolean-cast': 'error',
      'no-extra-label': 'off',
      'no-fallthrough': 'error',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'off',
      'no-implicit-globals': 'off',
      'no-implied-eval': 'off',
      'no-inline-comments': 'off',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-invalid-this': 'off',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'off',
      'no-label-var': 'off',
      'no-labels': 'off',
      'no-lone-blocks': 'off',
      'no-lonely-if': 'off',
      'no-loop-func': 'off',
      'no-loss-of-precision': 'error',
      'no-magic-numbers': 'off',
      'no-misleading-character-class': 'error',
      'no-multi-assign': 'off',
      'no-multi-str': 'off',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'off',
      'no-new': 'off',
      'no-new-func': 'off',
      'no-new-native-nonconstructor': 'error',
      'no-new-object': 'off',
      'no-new-wrappers': 'off',
      'no-nonoctal-decimal-escape': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'off',
      'no-param-reassign': 'off',
      'no-plusplus': 'off',
      'no-promise-executor-return': 'off',
      'no-proto': 'off',
      'no-prototype-builtins': 'error',
      'no-regex-spaces': 'error',
      'no-restricted-exports': 'off',
      'no-restricted-globals': 'off',
      'no-restricted-imports': 'off',
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
      'no-return-assign': 'off',
      'no-return-await': 'off',
      'no-script-url': 'off',
      'no-self-assign': 'error',
      'no-self-compare': 'off',
      'no-sequences': 'off',
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-ternary': 'off',
      'no-throw-literal': 'off',
      'no-undef-init': 'off',
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'off',
      'no-unneeded-ternary': 'off',
      'no-unreachable-loop': 'off',
      'no-unsafe-finally': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-expressions': 'off',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'off',
      'no-unused-vars': 'off', // TypeScript ESLint handles this
      'no-use-before-define': 'off',
      'no-useless-backreference': 'error',
      'no-useless-call': 'off',
      'no-useless-catch': 'error',
      'no-useless-computed-key': 'off',
      'no-useless-concat': 'off',
      'no-useless-constructor': 'off',
      'no-useless-escape': 'error',
      'no-useless-rename': 'off',
      'no-useless-return': 'off',
      'no-var': 'off',
      'no-void': 'off',
      'no-warning-comments': 'off',
      'no-with': 'error',
      'object-shorthand': 'off',
      'one-var': 'off',
      'one-var-declaration-per-line': 'off',
      'operator-assignment': 'off',
      'prefer-arrow-callback': 'error',
      'prefer-const': 'off',
      'prefer-destructuring': 'off',
      'prefer-exponentiation-operator': 'off',
      'prefer-named-capture-group': 'off',
      'prefer-numeric-literals': 'off',
      'prefer-object-has-own': 'off',
      'prefer-object-spread': 'off',
      'prefer-promise-reject-errors': 'off',
      'prefer-regex-literals': 'off',
      'prefer-rest-params': 'off',
      'prefer-spread': 'off',
      'prefer-template': 'off',
      radix: 'off',
      'require-atomic-updates': 'off',
      'require-await': 'off',
      'require-unicode-regexp': 'off',
      'require-yield': 'error',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'spaced-comment': 'off',
      strict: 'off',
      'symbol-description': 'off',
      'use-isnan': 'error',
      'vars-on-top': 'off',
      yoda: 'off',

      // Formatting rules disabled since Prettier handles formatting
      indent: 'off', // handled by prettier
      quotes: 'off', // handled by prettier
      semi: 'off', // handled by prettier
      'max-len': 'off', // handled by prettier
      'comma-dangle': 'off', // handled by prettier
    },
  },
  // Add prettier config to disable conflicting rules
  prettierConfig,
]

export default config
