-- Baseline neutral migration generated by drizzle-kit generate
-- The database already matches the TypeScript schema; no changes applied.
DO $$ BEGIN RAISE NOTICE '0021_giant_nextwave baseline noop'; END $$;
