import {
  isReviewServingReadContractKey,
  type NamedReviewFastCountKey,
  type ReviewServingFilterKey,
  type ReviewServingListMode,
  type ReviewServingProjectionComponent,
  type ReviewServingReadContract,
  type ReviewServingReadContractKey,
  reviewServingReadContractKeys,
} from './reviewServingContracts.ts'

export const reviewServingReadSurfaces = [
  'badge',
  'both',
  'bulk',
  'count',
  'detail',
  'export',
  'facet',
  'filter',
  'health',
  'human',
  'llm',
  'pdf',
  'promptPreview',
  'queue',
  'row',
  'search',
  'unassessed',
  'warning',
] as const

export type ReviewServingReadSurface = (typeof reviewServingReadSurfaces)[number]

export type ReviewServingReadContractRouteInventoryEntry = {
  contractKeys: readonly ReviewServingReadContractKey[]
  method: 'GET' | 'POST'
  mounted: boolean
  productRoute: string
  routeFile: string
  surfaces: readonly ReviewServingReadSurface[]
}

type ContractInput = Omit<
  ReviewServingReadContract,
  'allowsTempSpill' | 'maxEstimatedResultBytes' | 'maxResultRows' | 'timeoutMs'
> & {allowsTempSpill?: boolean; maxEstimatedResultBytes?: number; maxResultRows?: number; timeoutMs?: number}

const baseComponents = ['display', 'projectScope', 'selectedImport', 'payload'] as const
const llmComponents = [...baseComponents, 'llmStatus', 'posting', 'summary'] as const
const humanComponents = [...baseComponents, 'humanStatus', 'posting', 'summary'] as const
const bothComponents = [...baseComponents, 'llmStatus', 'humanStatus', 'posting', 'summary'] as const
const queueComponents = [
  'judgmentInputContent',
  'projectScope',
  'selectedImport',
  'llmStatus',
  'queue',
  'summary',
] as const
const defaultRowFilters = ['duplicateFlag', 'importRoute', 'publicationYear', 'searchTokenPrefix'] as const
const defaultReviewCounts = ['review.list.total', 'review.list.filteredTotal'] as const
const reviewArticleServingTable = 'mart.review_article_serving_v4'
const reviewArticlePayloadServingTable = 'mart.review_article_serving_payload_v4'
const reviewCountServingTable = 'mart.review_article_count_serving_v4'
const reviewFacetServingTable = 'mart.review_filter_facet_serving_v4'
const reviewFilterPostingServingTable = 'mart.review_article_filter_posting_serving_v4'
const reviewQueueServingTable = 'mart.review_unassessed_queue_serving_v4'
const reviewSearchServingTable = 'mart.review_title_search_serving_v4'
const reviewSnapshotManifestTable = 'app.review_serving_snapshot_manifest'
const countServingSort = {direction: 'asc', fields: ['count_kind', 'summary_definition_version', 'filter_key']} as const

const defineContract = (input: ContractInput): ReviewServingReadContract => {
  return {
    ...input,
    allowsTempSpill: input.allowsTempSpill ?? false,
    maxEstimatedResultBytes: input.maxEstimatedResultBytes ?? 2_000_000,
    maxResultRows: input.maxResultRows ?? input.maxPageSize,
    timeoutMs: input.timeoutMs ?? 5_000,
  }
}

const rowContract = (input: {
  allowedFilters: readonly ReviewServingFilterKey[]
  key: ReviewServingReadContractKey
  listMode: ReviewServingListMode
  namedFastCounts: readonly NamedReviewFastCountKey[]
  requiredComponents: readonly ReviewServingProjectionComponent[]
}) => {
  return defineContract({
    allowedFilters: input.allowedFilters,
    cursorFields: ['sort_key', 'article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: input.key,
    listMode: input.listMode,
    maxPageSize: 100,
    namedFastCounts: input.namedFastCounts,
    optionalComponents: ['search'],
    physicalAccessStrategy: 'orderedPrefix',
    requiredComponents: input.requiredComponents,
    searchMode: 'tokenPrefix',
    servingTable: reviewArticleServingTable,
    sort: {direction: 'desc', fields: ['sort_key', 'article_id']},
    workloadClass: 'foregroundReviewRows',
  })
}

export const reviewServingReadContractList = [
  rowContract({
    allowedFilters: [...defaultRowFilters, 'llmStatus', 'promptAnswer'],
    key: 'review.llm.rows',
    listMode: 'llm',
    namedFastCounts: [...defaultReviewCounts, 'review.llm.assessedByPrompt'],
    requiredComponents: llmComponents,
  }),
  defineContract({
    allowedFilters: [...defaultRowFilters, 'llmStatus', 'promptAnswer'],
    cursorFields: [],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.llm.count',
    listMode: 'llm',
    maxPageSize: 1,
    maxResultRows: 1,
    namedFastCounts: [...defaultReviewCounts, 'review.llm.assessedByPrompt', 'review.llm.unassessedByPrompt'],
    optionalComponents: [],
    physicalAccessStrategy: 'summaryLookup',
    requiredComponents: ['llmStatus', 'posting', 'queue', 'summary'],
    searchMode: 'none',
    servingTable: reviewCountServingTable,
    sort: countServingSort,
    workloadClass: 'foregroundReviewCount',
  }),
  rowContract({
    allowedFilters: [...defaultRowFilters, 'humanStatus', 'promptAnswer'],
    key: 'review.human.rows',
    listMode: 'human',
    namedFastCounts: [...defaultReviewCounts, 'review.human.reviewedByPrompt'],
    requiredComponents: humanComponents,
  }),
  defineContract({
    allowedFilters: [...defaultRowFilters, 'humanStatus', 'promptAnswer'],
    cursorFields: [],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.human.count',
    listMode: 'human',
    maxPageSize: 1,
    maxResultRows: 1,
    namedFastCounts: [...defaultReviewCounts, 'review.human.reviewedByPrompt'],
    optionalComponents: [],
    physicalAccessStrategy: 'summaryLookup',
    requiredComponents: ['humanStatus', 'posting', 'summary'],
    searchMode: 'none',
    servingTable: reviewCountServingTable,
    sort: countServingSort,
    workloadClass: 'foregroundReviewCount',
  }),
  rowContract({
    allowedFilters: [...defaultRowFilters, 'conflictFlag', 'humanStatus', 'llmStatus', 'promptAnswer'],
    key: 'review.both.rows',
    listMode: 'both',
    namedFastCounts: [...defaultReviewCounts, 'review.both.conflictByPrompt'],
    requiredComponents: bothComponents,
  }),
  defineContract({
    allowedFilters: [...defaultRowFilters, 'conflictFlag', 'humanStatus', 'llmStatus', 'promptAnswer'],
    cursorFields: [],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.both.count',
    listMode: 'both',
    maxPageSize: 1,
    maxResultRows: 1,
    namedFastCounts: [...defaultReviewCounts, 'review.both.conflictByPrompt'],
    optionalComponents: [],
    physicalAccessStrategy: 'summaryLookup',
    requiredComponents: ['llmStatus', 'humanStatus', 'posting', 'summary'],
    searchMode: 'none',
    servingTable: reviewCountServingTable,
    sort: countServingSort,
    workloadClass: 'foregroundReviewCount',
  }),
  rowContract({
    allowedFilters: ['importRoute', 'publicationYear', 'queueKind', 'searchTokenPrefix'],
    key: 'review.unassessed.rows',
    listMode: 'unassessed',
    namedFastCounts: ['review.queue.unassessedReady', 'review.llm.unassessedByPrompt'],
    requiredComponents: queueComponents,
  }),
  defineContract({
    allowedFilters: ['importRoute', 'publicationYear', 'queueKind'],
    cursorFields: [],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.unassessed.count',
    listMode: 'unassessed',
    maxPageSize: 1,
    maxResultRows: 1,
    namedFastCounts: ['review.queue.unassessedReady', 'review.llm.unassessedByPrompt'],
    optionalComponents: [],
    physicalAccessStrategy: 'summaryLookup',
    requiredComponents: ['queue', 'summary'],
    searchMode: 'none',
    servingTable: reviewCountServingTable,
    sort: countServingSort,
    workloadClass: 'foregroundReviewCount',
  }),
  defineContract({
    allowedFilters: [
      'articleId',
      'conflictFlag',
      'duplicateFlag',
      'humanStatus',
      'importRoute',
      'llmStatus',
      'promptAnswer',
      'publicationYear',
      'queueKind',
      'searchTokenPrefix',
    ],
    cursorFields: ['sort_key', 'article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.filters.postings',
    listMode: null,
    maxPageSize: 100,
    namedFastCounts: ['review.list.filteredTotal'],
    optionalComponents: ['search'],
    physicalAccessStrategy: 'postingIntersection',
    requiredComponents: ['posting', 'summary'],
    searchMode: 'tokenPrefix',
    servingTable: reviewFilterPostingServingTable,
    sort: {direction: 'desc', fields: ['sort_key', 'article_id']},
    workloadClass: 'foregroundReviewRows',
  }),
  defineContract({
    allowedFilters: [
      'conflictFlag',
      'duplicateFlag',
      'humanStatus',
      'importRoute',
      'llmStatus',
      'promptAnswer',
      'publicationYear',
    ],
    cursorFields: [],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.filters.facets',
    listMode: null,
    maxPageSize: 1,
    maxResultRows: 128,
    namedFastCounts: [
      'review.filter.duplicateFlag',
      'review.filter.importRoute',
      'review.filter.promptAnswer',
      'review.filter.publicationYear',
    ],
    optionalComponents: [],
    physicalAccessStrategy: 'summaryLookup',
    requiredComponents: ['posting', 'summary'],
    searchMode: 'none',
    servingTable: reviewFacetServingTable,
    sort: {direction: 'asc', fields: ['facet_key', 'facet_value']},
    workloadClass: 'foregroundReviewFacet',
  }),
  defineContract({
    allowedFilters: ['promptAnswer'],
    cursorFields: [],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.prompt.badges',
    listMode: null,
    maxPageSize: 1,
    maxResultRows: 512,
    namedFastCounts: [
      'review.both.conflictByPrompt',
      'review.human.reviewedByPrompt',
      'review.llm.assessedByPrompt',
      'review.llm.unassessedByPrompt',
    ],
    optionalComponents: [],
    physicalAccessStrategy: 'summaryLookup',
    requiredComponents: ['llmStatus', 'humanStatus', 'queue', 'summary'],
    searchMode: 'none',
    servingTable: reviewCountServingTable,
    sort: countServingSort,
    workloadClass: 'foregroundReviewCount',
  }),
  defineContract({
    allowedFilters: ['queueKind'],
    cursorFields: ['priority_bucket', 'activity_sort_at', 'article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.queue.unassessed',
    listMode: 'unassessed',
    maxPageSize: 100,
    namedFastCounts: ['review.queue.unassessedReady'],
    optionalComponents: [],
    physicalAccessStrategy: 'queueOrdering',
    requiredComponents: ['queue'],
    searchMode: 'none',
    servingTable: reviewQueueServingTable,
    sort: {direction: 'asc', fields: ['priority_bucket', 'activity_sort_at', 'article_id']},
    workloadClass: 'foregroundReviewQueue',
  }),
  defineContract({
    allowedFilters: ['articleId'],
    cursorFields: ['article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.detail.row',
    listMode: null,
    maxPageSize: 1,
    maxResultRows: 1,
    namedFastCounts: [],
    optionalComponents: [],
    physicalAccessStrategy: 'keyedLookup',
    requiredComponents: ['display', 'llmStatus', 'humanStatus', 'projectScope', 'selectedImport', 'summary'],
    searchMode: 'none',
    servingTable: reviewArticleServingTable,
    sort: {direction: 'asc', fields: ['article_id']},
    workloadClass: 'foregroundReviewRows',
  }),
  defineContract({
    allowedFilters: ['articleId'],
    cursorFields: ['article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.detail.payload',
    listMode: null,
    maxEstimatedResultBytes: 1_000_000,
    maxPageSize: 1,
    maxResultRows: 1,
    namedFastCounts: [],
    optionalComponents: [],
    physicalAccessStrategy: 'keyedLookup',
    requiredComponents: ['display', 'payload'],
    searchMode: 'none',
    servingTable: reviewArticlePayloadServingTable,
    sort: {direction: 'asc', fields: ['article_id']},
    workloadClass: 'foregroundReviewRows',
  }),
  defineContract({
    allowedFilters: [],
    cursorFields: ['updated_at', 'snapshot_id'],
    freshnessBehavior: 'allowStaleSnapshot',
    key: 'review.health.snapshot',
    listMode: null,
    maxPageSize: 1,
    maxResultRows: 1,
    namedFastCounts: ['review.list.total'],
    optionalComponents: ['queue', 'search'],
    physicalAccessStrategy: 'keyedLookup',
    requiredComponents: ['projectScope', 'summary'],
    searchMode: 'none',
    servingTable: reviewSnapshotManifestTable,
    sort: {direction: 'desc', fields: ['updated_at', 'snapshot_id']},
    workloadClass: 'reviewMaintenance',
  }),
  defineContract({
    allowedFilters: [],
    cursorFields: ['updated_at', 'snapshot_id'],
    freshnessBehavior: 'allowStaleSnapshot',
    key: 'review.warning.snapshot',
    listMode: null,
    maxPageSize: 8,
    namedFastCounts: ['review.list.total', 'review.queue.unassessedReady'],
    optionalComponents: ['search'],
    physicalAccessStrategy: 'keyedLookup',
    requiredComponents: ['projectScope', 'posting', 'queue', 'summary'],
    searchMode: 'none',
    servingTable: reviewSnapshotManifestTable,
    sort: {direction: 'desc', fields: ['updated_at', 'snapshot_id']},
    workloadClass: 'reviewMaintenance',
  }),
  defineContract({
    allowedFilters: [],
    cursorFields: ['article_created_at', 'article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.prompt.preview',
    listMode: null,
    maxEstimatedResultBytes: 1_000_000,
    maxPageSize: 1,
    maxResultRows: 1,
    namedFastCounts: [],
    optionalComponents: [],
    physicalAccessStrategy: 'orderedPrefix',
    requiredComponents: ['judgmentInputContent', 'projectScope', 'selectedImport', 'payload'],
    searchMode: 'none',
    servingTable: reviewArticlePayloadServingTable,
    sort: {direction: 'asc', fields: ['article_created_at', 'article_id']},
    workloadClass: 'foregroundReviewRows',
  }),
  defineContract({
    allowedFilters: [
      ...defaultRowFilters,
      'articleId',
      'conflictFlag',
      'humanStatus',
      'llmStatus',
      'promptAnswer',
      'queueKind',
    ],
    cursorFields: ['sort_key', 'article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.bulk.selection',
    listMode: null,
    maxEstimatedResultBytes: 500_000,
    maxPageSize: 1,
    maxResultRows: 0,
    namedFastCounts: [],
    optionalComponents: ['search'],
    physicalAccessStrategy: 'jobCriteria',
    requiredComponents: ['projectScope', 'posting', 'summary'],
    searchMode: 'tokenPrefix',
    servingTable: 'app.review_bulk_operation_job',
    sort: {direction: 'asc', fields: ['article_id']},
    workloadClass: 'bulkReviewJob',
  }),
  defineContract({
    allowedFilters: [...defaultRowFilters, 'conflictFlag', 'humanStatus', 'llmStatus', 'promptAnswer', 'sourceProject'],
    cursorFields: ['sort_key', 'article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.export.selection',
    listMode: null,
    maxEstimatedResultBytes: 500_000,
    maxPageSize: 1,
    maxResultRows: 0,
    namedFastCounts: [],
    optionalComponents: ['search'],
    physicalAccessStrategy: 'jobCriteria',
    requiredComponents: ['projectScope', 'posting', 'payload'],
    searchMode: 'tokenPrefix',
    servingTable: 'app.review_bulk_operation_job',
    sort: {direction: 'asc', fields: ['article_id']},
    workloadClass: 'bulkReviewJob',
  }),
  defineContract({
    allowedFilters: [
      ...defaultRowFilters,
      'articleId',
      'conflictFlag',
      'humanStatus',
      'llmStatus',
      'promptAnswer',
      'queueKind',
    ],
    cursorFields: ['sort_key', 'article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.pdf.selection',
    listMode: null,
    maxEstimatedResultBytes: 500_000,
    maxPageSize: 1,
    maxResultRows: 0,
    namedFastCounts: [],
    optionalComponents: ['search'],
    physicalAccessStrategy: 'jobCriteria',
    requiredComponents: ['projectScope', 'posting', 'payload'],
    searchMode: 'tokenPrefix',
    servingTable: 'app.review_bulk_operation_job',
    sort: {direction: 'asc', fields: ['article_id']},
    workloadClass: 'bulkReviewJob',
  }),
  defineContract({
    allowedFilters: ['searchTokenPrefix'],
    cursorFields: ['token', 'article_id'],
    freshnessBehavior: 'requireReadySnapshot',
    key: 'review.search.tokenPrefix',
    listMode: null,
    maxPageSize: 50,
    namedFastCounts: [],
    optionalComponents: [],
    physicalAccessStrategy: 'tokenPrefixIndex',
    requiredComponents: ['search'],
    searchMode: 'tokenPrefix',
    servingTable: reviewSearchServingTable,
    sort: {direction: 'asc', fields: ['token', 'article_id']},
    workloadClass: 'foregroundReviewSearch',
  }),
  defineContract({
    allowedFilters: ['searchTokenPrefix'],
    cursorFields: [],
    freshnessBehavior: 'asyncUnavailable',
    key: 'review.search.substringAsync',
    listMode: null,
    maxEstimatedResultBytes: 100_000,
    maxPageSize: 1,
    maxResultRows: 0,
    namedFastCounts: [],
    optionalComponents: ['search'],
    physicalAccessStrategy: 'jobCriteria',
    requiredComponents: ['search'],
    searchMode: 'substringAsync',
    servingTable: 'app.review_search_job',
    sort: {direction: 'asc', fields: ['article_id']},
    workloadClass: 'bulkReviewJob',
  }),
] satisfies readonly ReviewServingReadContract[]

export const reviewServingReadContractRouteInventory = [
  {
    contractKeys: [
      'review.llm.rows',
      'review.llm.count',
      'review.prompt.badges',
      'review.search.tokenPrefix',
      'review.search.substringAsync',
    ],
    method: 'POST',
    mounted: false,
    productRoute: '/api/articlesreviews',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesGetArticlesReviews.ts',
    surfaces: ['llm', 'row', 'count', 'badge', 'filter', 'search'],
  },
  {
    contractKeys: [
      'review.human.rows',
      'review.human.count',
      'review.search.tokenPrefix',
      'review.search.substringAsync',
    ],
    method: 'POST',
    mounted: false,
    productRoute: '/api/articlesreviewshuman',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesGetArticlesReviewsHuman.ts',
    surfaces: ['human', 'row', 'count', 'filter', 'search'],
  },
  {
    contractKeys: [
      'review.both.rows',
      'review.both.count',
      'review.search.tokenPrefix',
      'review.search.substringAsync',
    ],
    method: 'POST',
    mounted: false,
    productRoute: '/api/articlesreviewsboth',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesGetArticlesReviewsBoth.ts',
    surfaces: ['both', 'row', 'count', 'filter', 'search'],
  },
  {
    contractKeys: [
      'review.unassessed.rows',
      'review.unassessed.count',
      'review.queue.unassessed',
      'review.search.tokenPrefix',
      'review.search.substringAsync',
    ],
    method: 'POST',
    mounted: false,
    productRoute: '/api/articlesreviewsunassessed',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesGetArticlesReviewsUnassessed.ts',
    surfaces: ['unassessed', 'row', 'count', 'queue', 'filter', 'search'],
  },
  {
    contractKeys: ['review.filters.postings'],
    method: 'POST',
    mounted: false,
    productRoute: '/api/review-serving/filter-postings',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesGetArticlesReviews.ts',
    surfaces: ['filter'],
  },
  {
    contractKeys: ['review.filters.facets'],
    method: 'GET',
    mounted: false,
    productRoute: '/api/review-serving/filter-facets',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesGetArticlesReviewsFilters.ts',
    surfaces: ['facet'],
  },
  {
    contractKeys: ['review.detail.row', 'review.detail.payload', 'review.prompt.badges'],
    method: 'POST',
    mounted: false,
    productRoute: '/api/projectsreview',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesPostArticleReviewDetails.ts',
    surfaces: ['detail', 'row', 'badge'],
  },
  {
    contractKeys: ['review.warning.snapshot', 'review.health.snapshot'],
    method: 'POST',
    mounted: false,
    productRoute: '/api/review-serving/snapshot-status',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesGetReviewsWarnings.ts',
    surfaces: ['warning', 'health'],
  },
  {
    contractKeys: ['review.prompt.preview', 'review.detail.payload'],
    method: 'GET',
    mounted: false,
    productRoute: '/api/projects/:id/prompts/:promptId/preview',
    routeFile: 'src/server/routes/projectsRoutes/projectsRoutesGetPromptPreview.ts',
    surfaces: ['promptPreview', 'detail'],
  },
  {
    contractKeys: ['review.bulk.selection', 'review.pdf.selection'],
    method: 'POST',
    mounted: false,
    productRoute: '/api/articles/pdf-fetch-by-filter',
    routeFile: 'src/server/routes/ArticlesRoutes.ts',
    surfaces: ['bulk', 'pdf', 'filter'],
  },
  {
    contractKeys: ['review.pdf.selection'],
    method: 'POST',
    mounted: false,
    productRoute: '/api/articles/pdf-fetch-by-project',
    routeFile: 'src/server/routes/ArticlesRoutes.ts',
    surfaces: ['pdf', 'bulk'],
  },
  {
    contractKeys: ['review.export.selection'],
    method: 'POST',
    mounted: false,
    productRoute: '/api/projects/:id/export',
    routeFile: 'src/server/routes/ProjectExportRoutes.ts',
    surfaces: ['export', 'bulk'],
  },
] as const satisfies readonly ReviewServingReadContractRouteInventoryEntry[]

export const reviewServingReadContracts = reviewServingReadContractList.reduce<
  Record<ReviewServingReadContractKey, ReviewServingReadContract>
>(
  (contracts, contract) => {
    return {...contracts, [contract.key]: contract}
  },
  {} as Record<ReviewServingReadContractKey, ReviewServingReadContract>,
)

export const getReviewServingReadContract = (contractKey: string) => {
  return isReviewServingReadContractKey(contractKey) ? reviewServingReadContracts[contractKey] : null
}

export const getMissingReviewServingReadContractKeys = () => {
  return reviewServingReadContractKeys.filter((contractKey) => {
    return reviewServingReadContracts[contractKey] === undefined
  })
}
