/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/+__root'
import { Route as IndexRouteImport } from './routes/+index'
import { Route as ProjectsCreateRouteImport } from './routes/+projects/+create'
import { Route as SettingsIndexRouteImport } from './routes/+settings/+index'
import { Route as ProjectsIndexRouteImport } from './routes/+projects/+index'
import { Route as LoginIndexRouteImport } from './routes/+login/+index'
import { Route as LatestArticlesIndexRouteImport } from './routes/+latest-articles/+index'
import { Route as ProjectsIdHumanAssessmentRouteImport } from './routes/+projects/+$id/+humanAssessment'
import { Route as ProjectsIdEditRouteImport } from './routes/+projects/+$id/+edit'
import { Route as AdminDatasourcesCreateRouteImport } from './routes/+admin/+datasources/+create'
import { Route as ProjectsIdIndexRouteImport } from './routes/+projects/+$id/+index'
import { Route as AdminVllmIndexRouteImport } from './routes/+admin/+vllm/+index'
import { Route as AdminUsersIndexRouteImport } from './routes/+admin/+users/+index'
import { Route as AdminModelsIndexRouteImport } from './routes/+admin/+models/+index'
import { Route as AdminJobsIndexRouteImport } from './routes/+admin/+jobs/+index'
import { Route as AdminDatasourcesIndexRouteImport } from './routes/+admin/+datasources/+index'
import { Route as AdminAssessmentsIndexRouteImport } from './routes/+admin/+assessments/+index'
import { Route as AdminJobsIdUnassessed_articlesRouteImport } from './routes/+admin/+jobs/+$id/+unassessed_articles'
import { Route as AdminDatasourcesIdEditRouteImport } from './routes/+admin/+datasources/+$id/+edit'
import { Route as ProjectsIdReviewsIndexRouteImport } from './routes/+projects/+$id/+reviews/+index'
import { Route as ProjectsIdReviewsUnassessedIndexRouteImport } from './routes/+projects/+$id/+reviews-unassessed/+index'
import { Route as AdminJobsIdIndexRouteImport } from './routes/+admin/+jobs/+$id/+index'
import { Route as ProjectsIdReviewsArticleIdIndexRouteImport } from './routes/+projects/+$id/+reviews/+$articleId/+index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/projects/create',
  path: '/projects/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestArticlesIndexRoute = LatestArticlesIndexRouteImport.update({
  id: '/latest-articles/',
  path: '/latest-articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdHumanAssessmentRoute =
  ProjectsIdHumanAssessmentRouteImport.update({
    id: '/projects/$id/humanAssessment',
    path: '/projects/$id/humanAssessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/projects/$id/edit',
  path: '/projects/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDatasourcesCreateRoute = AdminDatasourcesCreateRouteImport.update({
  id: '/admin/datasources/create',
  path: '/admin/datasources/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVllmIndexRoute = AdminVllmIndexRouteImport.update({
  id: '/admin/vllm/',
  path: '/admin/vllm/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelsIndexRoute = AdminModelsIndexRouteImport.update({
  id: '/admin/models/',
  path: '/admin/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/admin/jobs/',
  path: '/admin/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDatasourcesIndexRoute = AdminDatasourcesIndexRouteImport.update({
  id: '/admin/datasources/',
  path: '/admin/datasources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssessmentsIndexRoute = AdminAssessmentsIndexRouteImport.update({
  id: '/admin/assessments/',
  path: '/admin/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsIdUnassessed_articlesRoute =
  AdminJobsIdUnassessed_articlesRouteImport.update({
    id: '/admin/jobs/$id/unassessed_articles',
    path: '/admin/jobs/$id/unassessed_articles',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDatasourcesIdEditRoute = AdminDatasourcesIdEditRouteImport.update({
  id: '/admin/datasources/$id/edit',
  path: '/admin/datasources/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdReviewsIndexRoute = ProjectsIdReviewsIndexRouteImport.update({
  id: '/projects/$id/reviews/',
  path: '/projects/$id/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdReviewsUnassessedIndexRoute =
  ProjectsIdReviewsUnassessedIndexRouteImport.update({
    id: '/projects/$id/reviews-unassessed/',
    path: '/projects/$id/reviews-unassessed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminJobsIdIndexRoute = AdminJobsIdIndexRouteImport.update({
  id: '/admin/jobs/$id/',
  path: '/admin/jobs/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdReviewsArticleIdIndexRoute =
  ProjectsIdReviewsArticleIdIndexRouteImport.update({
    id: '/projects/$id/reviews/$articleId/',
    path: '/projects/$id/reviews/$articleId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/latest-articles': typeof LatestArticlesIndexRoute
  '/login': typeof LoginIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/admin/assessments': typeof AdminAssessmentsIndexRoute
  '/admin/datasources': typeof AdminDatasourcesIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/models': typeof AdminModelsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/vllm': typeof AdminVllmIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/admin/datasources/create': typeof AdminDatasourcesCreateRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/humanAssessment': typeof ProjectsIdHumanAssessmentRoute
  '/admin/jobs/$id': typeof AdminJobsIdIndexRoute
  '/projects/$id/reviews-unassessed': typeof ProjectsIdReviewsUnassessedIndexRoute
  '/projects/$id/reviews': typeof ProjectsIdReviewsIndexRoute
  '/admin/datasources/$id/edit': typeof AdminDatasourcesIdEditRoute
  '/admin/jobs/$id/unassessed_articles': typeof AdminJobsIdUnassessed_articlesRoute
  '/projects/$id/reviews/$articleId': typeof ProjectsIdReviewsArticleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/latest-articles': typeof LatestArticlesIndexRoute
  '/login': typeof LoginIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/admin/assessments': typeof AdminAssessmentsIndexRoute
  '/admin/datasources': typeof AdminDatasourcesIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/models': typeof AdminModelsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/vllm': typeof AdminVllmIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/admin/datasources/create': typeof AdminDatasourcesCreateRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/humanAssessment': typeof ProjectsIdHumanAssessmentRoute
  '/admin/jobs/$id': typeof AdminJobsIdIndexRoute
  '/projects/$id/reviews-unassessed': typeof ProjectsIdReviewsUnassessedIndexRoute
  '/projects/$id/reviews': typeof ProjectsIdReviewsIndexRoute
  '/admin/datasources/$id/edit': typeof AdminDatasourcesIdEditRoute
  '/admin/jobs/$id/unassessed_articles': typeof AdminJobsIdUnassessed_articlesRoute
  '/projects/$id/reviews/$articleId': typeof ProjectsIdReviewsArticleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/latest-articles/': typeof LatestArticlesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/admin/assessments/': typeof AdminAssessmentsIndexRoute
  '/admin/datasources/': typeof AdminDatasourcesIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/models/': typeof AdminModelsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/vllm/': typeof AdminVllmIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/admin/datasources/create': typeof AdminDatasourcesCreateRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/humanAssessment': typeof ProjectsIdHumanAssessmentRoute
  '/admin/jobs/$id/': typeof AdminJobsIdIndexRoute
  '/projects/$id/reviews-unassessed/': typeof ProjectsIdReviewsUnassessedIndexRoute
  '/projects/$id/reviews/': typeof ProjectsIdReviewsIndexRoute
  '/admin/datasources/$id/edit': typeof AdminDatasourcesIdEditRoute
  '/admin/jobs/$id/unassessed_articles': typeof AdminJobsIdUnassessed_articlesRoute
  '/projects/$id/reviews/$articleId/': typeof ProjectsIdReviewsArticleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/latest-articles'
    | '/login'
    | '/projects'
    | '/settings'
    | '/projects/create'
    | '/admin/assessments'
    | '/admin/datasources'
    | '/admin/jobs'
    | '/admin/models'
    | '/admin/users'
    | '/admin/vllm'
    | '/projects/$id'
    | '/admin/datasources/create'
    | '/projects/$id/edit'
    | '/projects/$id/humanAssessment'
    | '/admin/jobs/$id'
    | '/projects/$id/reviews-unassessed'
    | '/projects/$id/reviews'
    | '/admin/datasources/$id/edit'
    | '/admin/jobs/$id/unassessed_articles'
    | '/projects/$id/reviews/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/latest-articles'
    | '/login'
    | '/projects'
    | '/settings'
    | '/projects/create'
    | '/admin/assessments'
    | '/admin/datasources'
    | '/admin/jobs'
    | '/admin/models'
    | '/admin/users'
    | '/admin/vllm'
    | '/projects/$id'
    | '/admin/datasources/create'
    | '/projects/$id/edit'
    | '/projects/$id/humanAssessment'
    | '/admin/jobs/$id'
    | '/projects/$id/reviews-unassessed'
    | '/projects/$id/reviews'
    | '/admin/datasources/$id/edit'
    | '/admin/jobs/$id/unassessed_articles'
    | '/projects/$id/reviews/$articleId'
  id:
    | '__root__'
    | '/'
    | '/latest-articles/'
    | '/login/'
    | '/projects/'
    | '/settings/'
    | '/projects/create'
    | '/admin/assessments/'
    | '/admin/datasources/'
    | '/admin/jobs/'
    | '/admin/models/'
    | '/admin/users/'
    | '/admin/vllm/'
    | '/projects/$id/'
    | '/admin/datasources/create'
    | '/projects/$id/edit'
    | '/projects/$id/humanAssessment'
    | '/admin/jobs/$id/'
    | '/projects/$id/reviews-unassessed/'
    | '/projects/$id/reviews/'
    | '/admin/datasources/$id/edit'
    | '/admin/jobs/$id/unassessed_articles'
    | '/projects/$id/reviews/$articleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LatestArticlesIndexRoute: typeof LatestArticlesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  AdminAssessmentsIndexRoute: typeof AdminAssessmentsIndexRoute
  AdminDatasourcesIndexRoute: typeof AdminDatasourcesIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminModelsIndexRoute: typeof AdminModelsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVllmIndexRoute: typeof AdminVllmIndexRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  AdminDatasourcesCreateRoute: typeof AdminDatasourcesCreateRoute
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
  ProjectsIdHumanAssessmentRoute: typeof ProjectsIdHumanAssessmentRoute
  AdminJobsIdIndexRoute: typeof AdminJobsIdIndexRoute
  ProjectsIdReviewsUnassessedIndexRoute: typeof ProjectsIdReviewsUnassessedIndexRoute
  ProjectsIdReviewsIndexRoute: typeof ProjectsIdReviewsIndexRoute
  AdminDatasourcesIdEditRoute: typeof AdminDatasourcesIdEditRoute
  AdminJobsIdUnassessed_articlesRoute: typeof AdminJobsIdUnassessed_articlesRoute
  ProjectsIdReviewsArticleIdIndexRoute: typeof ProjectsIdReviewsArticleIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest-articles/': {
      id: '/latest-articles/'
      path: '/latest-articles'
      fullPath: '/latest-articles'
      preLoaderRoute: typeof LatestArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/humanAssessment': {
      id: '/projects/$id/humanAssessment'
      path: '/projects/$id/humanAssessment'
      fullPath: '/projects/$id/humanAssessment'
      preLoaderRoute: typeof ProjectsIdHumanAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/projects/$id/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/datasources/create': {
      id: '/admin/datasources/create'
      path: '/admin/datasources/create'
      fullPath: '/admin/datasources/create'
      preLoaderRoute: typeof AdminDatasourcesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vllm/': {
      id: '/admin/vllm/'
      path: '/admin/vllm'
      fullPath: '/admin/vllm'
      preLoaderRoute: typeof AdminVllmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/models/': {
      id: '/admin/models/'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/datasources/': {
      id: '/admin/datasources/'
      path: '/admin/datasources'
      fullPath: '/admin/datasources'
      preLoaderRoute: typeof AdminDatasourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assessments/': {
      id: '/admin/assessments/'
      path: '/admin/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/$id/unassessed_articles': {
      id: '/admin/jobs/$id/unassessed_articles'
      path: '/admin/jobs/$id/unassessed_articles'
      fullPath: '/admin/jobs/$id/unassessed_articles'
      preLoaderRoute: typeof AdminJobsIdUnassessed_articlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/datasources/$id/edit': {
      id: '/admin/datasources/$id/edit'
      path: '/admin/datasources/$id/edit'
      fullPath: '/admin/datasources/$id/edit'
      preLoaderRoute: typeof AdminDatasourcesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/reviews/': {
      id: '/projects/$id/reviews/'
      path: '/projects/$id/reviews'
      fullPath: '/projects/$id/reviews'
      preLoaderRoute: typeof ProjectsIdReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/reviews-unassessed/': {
      id: '/projects/$id/reviews-unassessed/'
      path: '/projects/$id/reviews-unassessed'
      fullPath: '/projects/$id/reviews-unassessed'
      preLoaderRoute: typeof ProjectsIdReviewsUnassessedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs/$id/': {
      id: '/admin/jobs/$id/'
      path: '/admin/jobs/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AdminJobsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/reviews/$articleId/': {
      id: '/projects/$id/reviews/$articleId/'
      path: '/projects/$id/reviews/$articleId'
      fullPath: '/projects/$id/reviews/$articleId'
      preLoaderRoute: typeof ProjectsIdReviewsArticleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LatestArticlesIndexRoute: LatestArticlesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  AdminAssessmentsIndexRoute: AdminAssessmentsIndexRoute,
  AdminDatasourcesIndexRoute: AdminDatasourcesIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminModelsIndexRoute: AdminModelsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVllmIndexRoute: AdminVllmIndexRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  AdminDatasourcesCreateRoute: AdminDatasourcesCreateRoute,
  ProjectsIdEditRoute: ProjectsIdEditRoute,
  ProjectsIdHumanAssessmentRoute: ProjectsIdHumanAssessmentRoute,
  AdminJobsIdIndexRoute: AdminJobsIdIndexRoute,
  ProjectsIdReviewsUnassessedIndexRoute: ProjectsIdReviewsUnassessedIndexRoute,
  ProjectsIdReviewsIndexRoute: ProjectsIdReviewsIndexRoute,
  AdminDatasourcesIdEditRoute: AdminDatasourcesIdEditRoute,
  AdminJobsIdUnassessed_articlesRoute: AdminJobsIdUnassessed_articlesRoute,
  ProjectsIdReviewsArticleIdIndexRoute: ProjectsIdReviewsArticleIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
