DROP INDEX IF EXISTS mart.idx_review_filter_posting_stats_v4_lookup;
DROP INDEX IF EXISTS idx_review_filter_posting_stats_v4_lookup;
DROP INDEX IF EXISTS mart.idx_review_filter_posting_stats_v4_repaired_pk;
DROP INDEX IF EXISTS idx_review_filter_posting_stats_v4_repaired_pk;
DROP TABLE IF EXISTS mart.review_filter_posting_stats_v4;
