DROP INDEX IF EXISTS mart.idx_review_article_judgment_detail_serving_v4_repaired_pk;
DROP INDEX IF EXISTS idx_review_article_judgment_detail_serving_v4_repaired_pk;
DROP INDEX IF EXISTS mart.idx_review_article_judgment_detail_serving_v4_article;
DROP INDEX IF EXISTS idx_review_article_judgment_detail_serving_v4_article;
