DROP TABLE IF EXISTS app.review_rebuild_chunk_manifest_noindex_repair_0231;

CREATE TABLE app.review_rebuild_chunk_manifest_noindex_repair_0231 (
  chunk_id VARCHAR NOT NULL,
  project_id VARCHAR,
  projection_component VARCHAR NOT NULL,
  projection_identity VARCHAR NOT NULL,
  input_digest VARCHAR,
  input_watermark BIGINT NOT NULL DEFAULT 0,
  chunk_start_key VARCHAR NOT NULL,
  chunk_end_key VARCHAR NOT NULL,
  output_base_generation BIGINT NOT NULL DEFAULT 0,
  status VARCHAR NOT NULL DEFAULT 'pending',
  checksum VARCHAR,
  lease_owner VARCHAR,
  lease_expires_at TIMESTAMPTZ,
  last_error VARCHAR,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
  request_id VARCHAR,
  parent_chunk_id VARCHAR,
  split_depth INTEGER DEFAULT 0,
  snapshot_id VARCHAR,
  snapshot_count INTEGER DEFAULT 1,
  retry_count INTEGER DEFAULT 0,
  retry_after TIMESTAMPTZ,
  oom_category VARCHAR,
  over_budget_reason VARCHAR,
  estimated_input_rows BIGINT,
  max_input_rows BIGINT,
  actual_input_rows BIGINT,
  estimated_output_rows BIGINT,
  max_output_rows BIGINT,
  actual_output_rows BIGINT,
  estimated_output_bytes BIGINT,
  max_output_bytes BIGINT,
  actual_output_bytes BIGINT,
  estimated_payload_bytes BIGINT,
  max_payload_bytes BIGINT,
  actual_payload_bytes BIGINT,
  estimated_prompt_count BIGINT,
  max_prompt_count BIGINT,
  actual_prompt_count BIGINT,
  estimated_temp_bytes BIGINT,
  max_temp_bytes BIGINT,
  actual_temp_bytes BIGINT,
  duration_ms BIGINT,
  workload_class VARCHAR,
  admission_state VARCHAR DEFAULT 'admitted',
  budget_json JSON DEFAULT '{}',
  diagnostics_json JSON DEFAULT '{}'
);

INSERT INTO app.review_rebuild_chunk_manifest_noindex_repair_0231 (
  chunk_id,
  project_id,
  projection_component,
  projection_identity,
  input_digest,
  input_watermark,
  chunk_start_key,
  chunk_end_key,
  output_base_generation,
  status,
  checksum,
  lease_owner,
  lease_expires_at,
  last_error,
  started_at,
  completed_at,
  created_at,
  updated_at,
  request_id,
  parent_chunk_id,
  split_depth,
  snapshot_id,
  snapshot_count,
  retry_count,
  retry_after,
  oom_category,
  over_budget_reason,
  estimated_input_rows,
  max_input_rows,
  actual_input_rows,
  estimated_output_rows,
  max_output_rows,
  actual_output_rows,
  estimated_output_bytes,
  max_output_bytes,
  actual_output_bytes,
  estimated_payload_bytes,
  max_payload_bytes,
  actual_payload_bytes,
  estimated_prompt_count,
  max_prompt_count,
  actual_prompt_count,
  estimated_temp_bytes,
  max_temp_bytes,
  actual_temp_bytes,
  duration_ms,
  workload_class,
  admission_state,
  budget_json,
  diagnostics_json
)
SELECT
  chunk_id,
  project_id,
  projection_component,
  projection_identity,
  input_digest,
  input_watermark,
  chunk_start_key,
  chunk_end_key,
  output_base_generation,
  status,
  checksum,
  lease_owner,
  lease_expires_at,
  last_error,
  started_at,
  completed_at,
  created_at,
  updated_at,
  request_id,
  parent_chunk_id,
  split_depth,
  snapshot_id,
  snapshot_count,
  retry_count,
  retry_after,
  oom_category,
  over_budget_reason,
  estimated_input_rows,
  max_input_rows,
  actual_input_rows,
  estimated_output_rows,
  max_output_rows,
  actual_output_rows,
  estimated_output_bytes,
  max_output_bytes,
  actual_output_bytes,
  estimated_payload_bytes,
  max_payload_bytes,
  actual_payload_bytes,
  estimated_prompt_count,
  max_prompt_count,
  actual_prompt_count,
  estimated_temp_bytes,
  max_temp_bytes,
  actual_temp_bytes,
  duration_ms,
  workload_class,
  admission_state,
  budget_json,
  diagnostics_json
FROM (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY chunk_id
      ORDER BY
        CASE
          WHEN status = 'completed' THEN 0
          WHEN status = 'running' AND (lease_expires_at IS NULL OR lease_expires_at > current_timestamp) THEN 1
          WHEN admission_state = 'admitted' AND status = 'pending' THEN 2
          WHEN status = 'running' THEN 3
          WHEN status = 'failed' THEN 4
          WHEN status = 'blocked_over_budget' THEN 5
          WHEN status = 'quarantined' THEN 6
          ELSE 7
        END ASC,
        updated_at DESC NULLS LAST,
        completed_at DESC NULLS LAST,
        started_at DESC NULLS LAST,
        created_at DESC NULLS LAST,
        request_id DESC NULLS LAST,
        chunk_id DESC
    ) AS repair_rank
  FROM app.review_rebuild_chunk_manifest
)
WHERE repair_rank = 1;

DROP TABLE app.review_rebuild_chunk_manifest;

ALTER TABLE app.review_rebuild_chunk_manifest_noindex_repair_0231
RENAME TO review_rebuild_chunk_manifest;
