DROP INDEX `article_route_link_article_idx`;--> statement-breakpoint
DROP INDEX `article_route_link_route_idx`;--> statement-breakpoint
DROP INDEX `article_route_link_updated_idx`;--> statement-breakpoint
DROP INDEX `articles_article_created_created_id_idx`;--> statement-breakpoint
DROP INDEX `articles_created_idx`;--> statement-breakpoint
DROP INDEX `articles_article_updated_idx`;--> statement-breakpoint
DROP INDEX `articles_import_route_article_created_idx`;--> statement-breakpoint
DROP INDEX `articles_updated_idx`;--> statement-breakpoint
DROP INDEX `articles_updated_id_idx`;--> statement-breakpoint
DROP INDEX `articles_openalex_id_unique`;--> statement-breakpoint
DROP INDEX `articles_full_text_conversion_status_idx`;--> statement-breakpoint
DROP INDEX `comparison_project_archived_idx`;--> statement-breakpoint
DROP INDEX `comparison_project_created_idx`;--> statement-breakpoint
DROP INDEX `comparison_project_prompt_project_idx`;--> statement-breakpoint
DROP INDEX `comparison_project_prompt_prompt_idx`;--> statement-breakpoint
DROP INDEX `comparison_project_prompt_project_order_idx`;--> statement-breakpoint
DROP INDEX `comparison_project_route_link_project_idx`;--> statement-breakpoint
DROP INDEX `comparison_project_route_link_route_idx`;--> statement-breakpoint
DROP INDEX `datasource_route_link_datasource_idx`;--> statement-breakpoint
DROP INDEX `datasource_route_link_route_idx`;--> statement-breakpoint
DROP INDEX `import_route_active_idx`;--> statement-breakpoint
DROP INDEX `judgments_article_prompt_idx`;--> statement-breakpoint
DROP INDEX `judgments_prompt_article_idx`;--> statement-breakpoint
DROP INDEX `judgments_article_prompt_model_idx`;--> statement-breakpoint
DROP INDEX `judgments_article_prompt_model_content_idx`;--> statement-breakpoint
DROP INDEX `judgments_updated_idx`;--> statement-breakpoint
DROP INDEX `judgments_updated_id_deleted_idx`;--> statement-breakpoint
DROP INDEX `judgments_created_idx`;--> statement-breakpoint
DROP INDEX `judgments_project_idx`;--> statement-breakpoint
DROP INDEX `judgments_deleted_at_idx`;--> statement-breakpoint
DROP INDEX `judgments_deleted_updated_idx`;--> statement-breakpoint
DROP INDEX `judgments_human_article_prompt_idx`;--> statement-breakpoint
DROP INDEX `judgments_human_prompt_article_idx`;--> statement-breakpoint
DROP INDEX `judgments_human_project_idx`;--> statement-breakpoint
DROP INDEX `judgments_human_prompt_article_answer_idx`;--> statement-breakpoint
DROP INDEX `judgments_human_updated_idx`;--> statement-breakpoint
DROP INDEX `judgments_jobs_project_idx`;--> statement-breakpoint
DROP INDEX `judgments_jobs_prompts_job_idx`;--> statement-breakpoint
DROP INDEX `judgments_jobs_prompts_job_status_idx`;--> statement-breakpoint
DROP INDEX `llm_status_ts_idx`;--> statement-breakpoint
DROP INDEX `llm_status_engine_instance_ts_idx`;--> statement-breakpoint
DROP INDEX `llm_status_model_ts_idx`;--> statement-breakpoint
DROP INDEX `nvidia_smi_ts_idx`;--> statement-breakpoint
DROP INDEX `nvidia_smi_instance_ts_idx`;--> statement-breakpoint
DROP INDEX `nvidia_smi_gpu_uuid_ts_idx`;--> statement-breakpoint
DROP INDEX `project_articles_project_idx`;--> statement-breakpoint
DROP INDEX `project_articles_article_idx`;--> statement-breakpoint
DROP INDEX `project_articles_imported_from_project_idx`;--> statement-breakpoint
DROP INDEX `project_prompts_project_idx`;--> statement-breakpoint
DROP INDEX `project_prompts_prompt_idx`;--> statement-breakpoint
DROP INDEX `project_prompts_project_order_idx`;--> statement-breakpoint
DROP INDEX `project_route_link_project_idx`;--> statement-breakpoint
DROP INDEX `project_route_link_route_idx`;--> statement-breakpoint
DROP INDEX `prompts_archived_idx`;--> statement-breakpoint
DROP INDEX `token_use_job_created_idx`;--> statement-breakpoint
DROP INDEX `token_use_updated_idx`;